TOPDIR = ..

PLATFORMS = rosco_m68k

TARGET_LIBS = ll_api

SRCS_ll_api = vram_alloc.c xosera_ll.c debug_print.c image_loader.c

include $(TOPDIR)/build/Make.Defaults
include $(TOPDIR)/build/Make.Rules
